#!/bin/sh


release_file=/etc/os-release

if grep -q "Arch" $release_file
then
	# The host is based.on Arch, run the pacman update command
	sudo pacman -Syu

fi

if grep -q "debian" $release_file || grep -q "Ubuntu" $release_file
then
	# The host is based on debian or Ubuntu,
	# Run the apt version of the command
	apt -y update
	apt -y dist-upgrade

fi
