---

- hosts: all
  become: true
  tasks:
  
   - name: install apache packages
     package:
       name: 
            - apache2
            - libapache2-mod-php
       state: latest 
       update_cache: yes
     when: ansible_distribution == "Ubuntu"
   

   - name: install apache and php on Fedroa
     dnf:
       name:
            - httpd
            - php
       state: latest
       update_cache: yes
     when: ansible_distribution == "Fedora"
